apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescale:5432
    database: ${DB_NAME:-waterwheel_simulation}
    user: ${DB_USER:-postgres}
    secureJsonData:
      password: ${DB_PASSWORD:-postgres}
    jsonData:
      postgresVersion: 1600
      timescaledb: true
      sslmode: disable
    editable: true
